/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_apt_JNIbfcp_JNIbfcpclass */

#ifndef _Included_com_example_apt_JNIbfcp_JNIbfcpclass
#define _Included_com_example_apt_JNIbfcp_JNIbfcpclass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_apt_JNIbfcp_JNIbfcpclass
 * Method:    bfcp_build_message_Hello
 * Signature: (Lcom/example/apt/JNIbfcp/bfcp_entity;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_apt_JNIbfcp_JNIbfcpclass_bfcp_1build_1message_1Hello
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
